//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST.SOAP.Tests.ServiceSOAP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSOAP.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse HelloWorld(REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse> HelloWorldAsync(REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name lista from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumList", ReplyAction="*")]
        REST.SOAP.Tests.ServiceSOAP.SumListResponse SumList(REST.SOAP.Tests.ServiceSOAP.SumListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SumList", ReplyAction="*")]
        System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.SumListResponse> SumListAsync(REST.SOAP.Tests.ServiceSOAP.SumListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public REST.SOAP.Tests.ServiceSOAP.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(REST.SOAP.Tests.ServiceSOAP.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public REST.SOAP.Tests.ServiceSOAP.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(REST.SOAP.Tests.ServiceSOAP.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumList", Namespace="http://tempuri.org/", Order=0)]
        public REST.SOAP.Tests.ServiceSOAP.SumListRequestBody Body;
        
        public SumListRequest() {
        }
        
        public SumListRequest(REST.SOAP.Tests.ServiceSOAP.SumListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public REST.SOAP.Tests.ServiceSOAP.ArrayOfInt lista;
        
        public SumListRequestBody() {
        }
        
        public SumListRequestBody(REST.SOAP.Tests.ServiceSOAP.ArrayOfInt lista) {
            this.lista = lista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumListResponse", Namespace="http://tempuri.org/", Order=0)]
        public REST.SOAP.Tests.ServiceSOAP.SumListResponseBody Body;
        
        public SumListResponse() {
        }
        
        public SumListResponse(REST.SOAP.Tests.ServiceSOAP.SumListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SumListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SumListResult;
        
        public SumListResponseBody() {
        }
        
        public SumListResponseBody(int SumListResult) {
            this.SumListResult = SumListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : REST.SOAP.Tests.ServiceSOAP.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<REST.SOAP.Tests.ServiceSOAP.WebService1Soap>, REST.SOAP.Tests.ServiceSOAP.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse REST.SOAP.Tests.ServiceSOAP.WebService1Soap.HelloWorld(REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest inValue = new REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest();
            inValue.Body = new REST.SOAP.Tests.ServiceSOAP.HelloWorldRequestBody();
            REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse retVal = ((REST.SOAP.Tests.ServiceSOAP.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse> REST.SOAP.Tests.ServiceSOAP.WebService1Soap.HelloWorldAsync(REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.HelloWorldResponse> HelloWorldAsync() {
            REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest inValue = new REST.SOAP.Tests.ServiceSOAP.HelloWorldRequest();
            inValue.Body = new REST.SOAP.Tests.ServiceSOAP.HelloWorldRequestBody();
            return ((REST.SOAP.Tests.ServiceSOAP.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        REST.SOAP.Tests.ServiceSOAP.SumListResponse REST.SOAP.Tests.ServiceSOAP.WebService1Soap.SumList(REST.SOAP.Tests.ServiceSOAP.SumListRequest request) {
            return base.Channel.SumList(request);
        }
        
        public int SumList(REST.SOAP.Tests.ServiceSOAP.ArrayOfInt lista) {
            REST.SOAP.Tests.ServiceSOAP.SumListRequest inValue = new REST.SOAP.Tests.ServiceSOAP.SumListRequest();
            inValue.Body = new REST.SOAP.Tests.ServiceSOAP.SumListRequestBody();
            inValue.Body.lista = lista;
            REST.SOAP.Tests.ServiceSOAP.SumListResponse retVal = ((REST.SOAP.Tests.ServiceSOAP.WebService1Soap)(this)).SumList(inValue);
            return retVal.Body.SumListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.SumListResponse> REST.SOAP.Tests.ServiceSOAP.WebService1Soap.SumListAsync(REST.SOAP.Tests.ServiceSOAP.SumListRequest request) {
            return base.Channel.SumListAsync(request);
        }
        
        public System.Threading.Tasks.Task<REST.SOAP.Tests.ServiceSOAP.SumListResponse> SumListAsync(REST.SOAP.Tests.ServiceSOAP.ArrayOfInt lista) {
            REST.SOAP.Tests.ServiceSOAP.SumListRequest inValue = new REST.SOAP.Tests.ServiceSOAP.SumListRequest();
            inValue.Body = new REST.SOAP.Tests.ServiceSOAP.SumListRequestBody();
            inValue.Body.lista = lista;
            return ((REST.SOAP.Tests.ServiceSOAP.WebService1Soap)(this)).SumListAsync(inValue);
        }
    }
}
